# Generated by Django 4.2.3 on 2023-11-13 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_pricing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class_category",
            name="amount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.pricing",
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="member_type",
            field=models.CharField(max_length=255),
        ),
    ]
