# Generated by Django 4.2.3 on 2023-11-13 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_delete_premiummemberpricing_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pricing",
            name="service",
        ),
        migrations.AddField(
            model_name="service",
            name="member_type",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.pricing",
            ),
        ),
    ]
