# Generated by Django 4.2.3 on 2023-11-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_remove_pricing_service_service_member_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("imgUrl", models.ImageField(upload_to="media/")),
                ("description", models.TextField()),
            ],
        ),
    ]
